version: '3.9'

networks:
  lablan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  web-01:
    image: laurakarangwa/nutrition:web01_latest
    container_name: web-01
    hostname: web-01
    networks:
      lablan:
        ipv4_address: 172.20.0.11
    ports:
      - "2211:22"
      - "8080:80"
    command: nginx -g "daemon off;"

  web-02:
    image: laurakarangwa/nutrition:web02_latest
    container_name: web-02
    hostname: web-02
    networks:
      lablan:
        ipv4_address: 172.20.0.12
    ports:
      - "2212:22"
      - "8081:80"
    command: nginx -g "daemon off;"

  lb-01:
    image: laurakarangwa/nutrition:lb01_latest
    container_name: lb-01
    hostname: lb-01
    networks:
      lablan:
        ipv4_address: 172.20.0.10
    ports:
      - "2210:22"
      - "8082:80"
    command: haproxy -f /etc/haproxy/haproxy.cfg -db